### ISSUE TITLE
Do not pass serf encrypt key as argument to the script (run-consul)

### ISSUE THREAD

**Issue by opdecirkel** [hashicorp/terraform-google-consul#17]
https://github.com/hashicorp/terraform-google-consul/blob/46e1930d04a40caaf9fd096f033311aa6d88e1cc/modules/run-consul/run-consul#L278

There are various ways a script argument can leak. An example (in context of this project) is GCP instance startup scripts is viewable by accounts with low privileges (such as viewer role). This makes command line arguments not suitable for passing secrets (by value).
One approach to mitigate this it to store the encryption key in a file and then pass the path as script argument. (Very similar to what is done with the TLS key in terraform-google-vault)

**Comment by josh-padnick** [comment]
You raise a fair point, and I definitely agree that users should not be passing the encryption key in plain text to `run-consul`. But it seems unnecessarily limiting to require the user to store their password in a file. 

I can think of a few ways users can more securely pass in the password:

- Store the password in a file somehow (e.g. you write the file at boot) and pass in the argument as `$(cat /path/to/file)`.
- Use an environment variable. 
- In the startup script, download your password and save it in a local var only, passing the var instead of a literal to the `encrypt-key` argument.

If you think any of these are worth explicitly documenting in the docs, PRs are welcome! In the meantime, I'm going to close this issue as I believe I've addressed your concern.
